# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_udnGEHsqNfuSaQ6aoXalCZvFq2NASyG
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os

# --- 1. KONFIGURASI HALAMAN ---
st.set_page_config(
    page_title="Prediksi Hujan Besok - Kelompok 3",
    page_icon="🌧️",
    layout="wide"
)

# --- 2. FUNGSI LOAD MODEL (MODIFIED) ---
@st.cache_resource
def load_model():
    # Menggunakan nama file model terbaru yang Anda unggah
    model_path = 'xgboost_roc_auc_tuned_model.pkl'

    if not os.path.exists(model_path):
        return None

    try:
        model_raw = joblib.load(model_path)
        # Menangani jika model dibungkus dalam GridSearchCV/RandomizedSearchCV
        if hasattr(model_raw, 'best_estimator_'):
            return model_raw.best_estimator_
        return model_raw
    except Exception as e:
        st.error(f"Error saat memuat model: {e}")
        return None

model = load_model()

# --- 3. DAFTAR FITUR (105 KOLOM) ---
# Pastikan urutan ini sama persis dengan X_train.columns saat training
FEATURE_NAMES = [
    'MaxTemp', 'Sunshine', 'WindGustSpeed', 'Humidity9am', 'Humidity3pm',
    'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp3pm',
    'Rainfall_log', 'Location_Albany', 'Location_Albury', 'Location_AliceSprings',
    'Location_BadgerysCreek', 'Location_Ballarat', 'Location_Bendigo', 'Location_Brisbane',
    'Location_Cairns', 'Location_Canberra', 'Location_Cobar', 'Location_CoffsHarbour',
    'Location_Dartmoor', 'Location_Darwin', 'Location_GoldCoast', 'Location_Hobart',
    'Location_Katherine', 'Location_Launceston', 'Location_Melbourne',
    'Location_MelbourneAirport', 'Location_Mildura', 'Location_Moree',
    'Location_MountGambier', 'Location_MountGinini', 'Location_Newcastle',
    'Location_Nhil', 'Location_NorahHead', 'Location_NorfolkIsland', 'Location_Nuriootpa',
    'Location_PearceRAAF', 'Location_Penrith', 'Location_Perth', 'Location_PerthAirport',
    'Location_Portland', 'Location_Richmond', 'Location_Sale', 'Location_SalmonGums',
    'Location_Sydney', 'Location_SydneyAirport', 'Location_Townsville',
    'Location_Tuggeranong', 'Location_Uluru', 'Location_WaggaWagga', 'Location_Walpole',
    'Location_Watsonia', 'Location_Williamtown', 'Location_Witchcliffe',
    'Location_Wollongong', 'Location_Woomera', 'WindGustDir_ENE', 'WindGustDir_ESE',
    'WindGustDir_N', 'WindGustDir_NE', 'WindGustDir_NNE', 'WindGustDir_NNW',
    'WindGustDir_NW', 'WindGustDir_S', 'WindGustDir_SE', 'WindGustDir_SSE',
    'WindGustDir_SSW', 'WindGustDir_SW', 'WindGustDir_W', 'WindGustDir_WNW',
    'WindGustDir_WSW', 'WindDir9am_ENE', 'WindDir9am_ESE', 'WindDir9am_N',
    'WindDir9am_NE', 'WindDir9am_NNE', 'WindDir9am_NNW', 'WindDir9am_NW',
    'WindDir9am_S', 'WindDir9am_SE', 'WindDir9am_SSE', 'WindDir9am_SSW',
    'WindDir9am_SW', 'WindDir9am_W', 'WindDir9am_WNW', 'WindDir9am_WSW',
    'WindDir3pm_ENE', 'WindDir3pm_ESE', 'WindDir3pm_N', 'WindDir3pm_NE',
    'WindDir3pm_NNE', 'WindDir3pm_NNW', 'WindDir3pm_NW', 'WindDir3pm_S',
    'WindDir3pm_SE', 'WindDir3pm_SSE', 'WindDir3pm_SSW', 'WindDir3pm_SW',
    'WindDir3pm_W', 'WindDir3pm_WNW', 'WindDir3pm_WSW', 'RainToday_Yes'
]

# --- 4. ANTARMUKA INPUT ---
st.title("🌧️ Neurathink Rain Prediction System")
st.info("Aplikasi ini digunakan untuk memprediksi apakah besok akan hujan atau tidak berdasarkan parameter cuaca harian di Australia. 
Model: XGBoost Optimized for ROC-AUC Score")

if model is None:
    st.error("⚠️ File 'xgboost_roc_auc_tuned_model.pkl' tidak ditemukan di direktori aktif.")
    st.stop()

with st.sidebar:
    st.header("Input Parameter Cuaca")

    # Numerik
    max_temp = st.number_input("Max Temp (°C)", value=25.0)
    sunshine = st.number_input("Sunshine", value=8.0)
    wind_speed = st.number_input("Wind Gust Speed (km/h)", value=40.0)
    h_9am = st.slider("Humidity 9am (%)", 0, 100, 60)
    h_3pm = st.slider("Humidity 3pm (%)", 0, 100, 50)
    p_9am = st.number_input("Pressure 9am (hPa)", value=1015.0)
    p_3pm = st.number_input("Pressure 3pm (hPa)", value=1010.0)
    c_9am = st.slider("Cloud 9am (0-9)", 0, 9, 4)
    c_3pm = st.slider("Cloud 3pm (0-9)", 0, 9, 4)
    t_3pm = st.number_input("Temp 3pm (°C)", value=22.0)
    rainfall = st.number_input("Rainfall Today (mm)", value=0.0)

    # Kategorikal
    location = st.selectbox("Location", sorted([f.split('_')[1] for f in FEATURE_NAMES if "Location_" in f]))
    wg_dir = st.selectbox("Wind Gust Dir", sorted([f.split('_')[1] for f in FEATURE_NAMES if "WindGustDir_" in f]))
    w9_dir = st.selectbox("Wind Dir 9am", sorted([f.split('_')[1] for f in FEATURE_NAMES if "WindDir9am_" in f]))
    w3_dir = st.selectbox("Wind Dir 3pm", sorted([f.split('_')[1] for f in FEATURE_NAMES if "WindDir3pm_" in f]))
    rain_today = st.radio("Rain Today?", ["No", "Yes"])

# --- 5. LOGIKA PREDIKSI ---
if st.button("Jalankan Prediksi", use_container_width=True):
    # Buat DataFrame kosong dengan semua fitur bernilai 0
    input_df = pd.DataFrame(0.0, index=[0], columns=FEATURE_NAMES)

    # Isi nilai numerik
    input_df['MaxTemp'] = max_temp
    input_df['Sunshine'] = sunshine
    input_df['WindGustSpeed'] = wind_speed
    input_df['Humidity9am'] = h_9am
    input_df['Humidity3pm'] = h_3pm
    input_df['Pressure9am'] = p_9am
    input_df['Pressure3pm'] = p_3pm
    input_df['Cloud9am'] = c_9am
    input_df['Cloud3pm'] = c_3pm
    input_df['Temp3pm'] = t_3pm
    input_df['Rainfall_log'] = np.log1p(rainfall) # Transformasi log sesuai notebook

    # Isi nilai One-Hot Encoding
    if f"Location_{location}" in FEATURE_NAMES: input_df[f"Location_{location}"] = 1.0
    if f"WindGustDir_{wg_dir}" in FEATURE_NAMES: input_df[f"WindGustDir_{wg_dir}"] = 1.0
    if f"WindDir9am_{w9_dir}" in FEATURE_NAMES: input_df[f"WindDir9am_{w9_dir}"] = 1.0
    if f"WindDir3pm_{w3_dir}" in FEATURE_NAMES: input_df[f"WindDir3pm_{w3_dir}"] = 1.0
    if rain_today == "Yes": input_df["RainToday_Yes"] = 1.0

    # Prediksi
    try:
        # Menjamin urutan kolom sesuai model
        input_df = input_df[FEATURE_NAMES]

        res = model.predict(input_df)
        prob = model.predict_proba(input_df)

        st.divider()
        col1, col2 = st.columns(2)
        col1.metric("Probabilitas Hujan", f"{prob[0][1]:.2%}")
        col2.metric("Probabilitas Cerah", f"{prob[0][0]:.2%}")

        if res[0] == 1:
            st.error("### 🌧️ Hasil: Besok diprediksi AKAN HUJAN")
        else:
            st.success("### ☀️ Hasil: Besok diprediksi TIDAK HUJAN")

    except Exception as e:
        st.error(f"Gagal melakukan prediksi: {e}")

st.sidebar.markdown("---")
st.sidebar.caption("Neurathink - Kelompok 3")
